apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-tad

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: main

images:
  - name: tad-image
    newName: ghcr.io/minbzk/tad
    newTag: main@sha256:84b644d8da3405edb2622060174bdddb5f47aeeef0af18d0d95a4283da291628

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: tad.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: tad.prd.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.prd.apps.digilab.network
