apiVersion: v1
kind: Secret
metadata:
    name: sec-postgres
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+BJUkaEc6/UWdj7oY0kQ0Q==,iv:Z20jv/lp7uyH5vxcC5T3jpZ/DpdDGsq9LUU6Ap+AzSQ=,tag:kkXAdX+iIlFcBpIHTpDxPw==,type:str]
    username: ENC[AES256_GCM,data:h6bq,iv:0c/I+ULLzSJ4pUtsdOAV2sUiT545Ct2RAylymwHI+PU=,tag:M8W8Z8881AiCAsKOT4UzpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0deq3t66yld72t4p8eawngpreffrsvztaffhj7f3wccercdx4psy5mvl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MStaRjV0RGUrNU5BSWhD
            OEZDTmxSU0JDTTRaY3IwbGw0TW1EWlVzMERZClJhTEdIZ01ieEJuQ1VkOVp2dHRa
            V1R2YkxvNmVMbThLSk15eFQ2SzZTb0UKLS0tIHpHY1lsUDRrZkowWmdaMzdmQklT
            YWl0aCsyVkpORGFsS2JrYjVhUTZ2UFEKv0PUtKIdu+16MIVFsdBtJ8JV0Ua7MY5N
            7Yy1I9rHEcR8B4QO7/7wo5JgrGVZz15h7gnx4ZU9OHynaBCE6D38UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T20:06:38Z"
    mac: ENC[AES256_GCM,data:WVZ4UFFt+GNLJcBTfaIo5PjIFeR/9e/37jTKgS/tkdP0oBtAp+MhJSU7MKddYy9SYKeCEon84Q/r1uy/6IZYDXFv/+u1T6OMD8uzTTlqascVGdaO4duMbw341lMW8lgigQYxEpvqJZxmPaJGQVl0gqREpTIBqJcTex8iE7U537M=,iv:CWpMafRbKqcNhyMPRz55m5cbSHCXlTloxbCAl100Az0=,tag:kNmgfbkOSwFV75fenDvpCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
