apiVersion: v1
kind: Secret
metadata:
    name: sec-postgres-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fdK9wlinQQUTlH62Qw3kpQ==,iv:DlG0qTFNavfluwJHQyZxyByIZAXlgf8uHzbGK0cvBIs=,tag:n/MpXwNq3EcI6dqmSDQbhg==,type:str]
    username: ENC[AES256_GCM,data:C8C7dsv/2lE=,iv:xs8JFKrg1bD0NN1XchKht7YP3GBM3pDSmVF9le4+MuQ=,tag:8RPEYtoJd4qrMVvBCORprA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0deq3t66yld72t4p8eawngpreffrsvztaffhj7f3wccercdx4psy5mvl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBanhjNGx5OW5nVGxTVi9l
            dC9jOCtSV2Rlazh2WG42bVBDOCtBTU9Nc1IwClVNQ2VRd1ZwRWl2K2FUdUJFcHhr
            Q0NhL2FvazRKUVRqb3VlNzk2NVU4QjgKLS0tIHo1b29wTEg0SGZWcVlDdXVSeTJ1
            K1c5RnVZRUk5TStsWXlIYjQ0SkhMV0EK2O7E4iZBQlP77IpJUqpOndvO//7qdFgb
            4/XNm+qcB4il/nYzevmVp7cwUCnzmkKmMXHYgdgxq/rojGKZ521cxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-13T19:25:34Z"
    mac: ENC[AES256_GCM,data:aH2VC+lQ69DJe2QqtbZB8glV7viq1A3EVLzeltzFCDpWv+3ZMqYtOLUY1iZ342b1LXXWaV5XFo+msLtJ/HtydP5corADphvrNFAAxCQIg5RNc2ChYlf6+7ZSVvTvKFw3YwtoRRakaoTVdUqZCJ6bibIeuaCAaAcTcAUTNqTkJ6E=,iv:376yN0MJ5IFSEuagtEA8KpjQkB6AsHjeaO8LVm3E5xE=,tag:ZjM9WGtKBLUh7eQO5Tut4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
