apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: amt
    spec:
      automountServiceAccountToken: false
      containers:
        - image: amt-image
          name: amt
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 700m
              memory: 128Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: 500m
              memory: 64Mi
              ephemeral-storage: "2Gi"
          env:
            - name: APP_DATABASE_SCHEME
              value: postgresql
            - name: APP_DATABASE_SERVER
              value: amt-cluster-db-rw
            - name: APP_DATABASE_DRIVER
              value: "asyncpg"
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sec-oidc
                  key: client_id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sec-oidc
                  key: client_secret
            - name: APP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: sec-postgres
                  key: username
            - name: APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sec-postgres
                  key: password
            - name: APP_DATABASE_DB
              value: amt
            - name: LOGGING_LEVEL
              value: INFO
            - name: ENVIRONMENT
              value: production
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /health/live
              port: 8000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
      imagePullSecrets:
        - name: minbzk-registry
