apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio

    spec:
      automountServiceAccountToken: false
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-11-07T00-52-20Z
        command: ["minio", "server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000
        - containerPort: 9001
        resources:
          limits:
            cpu: 700m
            memory: 128Mi
            ephemeral-storage: "2Gi"
          requests:
            cpu: 500m
            memory: 64Mi
            ephemeral-storage: "2Gi"
        env:
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sec-minio
              key: minio_root_password
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: sec-minio
              key: minio_root_user
        volumeMounts:
        - name: minio-pv-storage
          mountPath: /data
      volumes:
      - name: minio-pv-storage
        persistentVolumeClaim:
          claimName: pvc-minio
