apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - cnpg-transformer.yaml

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - horizontalpodautoscaler.yaml
  - deployment-pgadmin.yaml
  - deployment-minio.yaml
  - service-pgadmin.yaml
  - ingress-pgadmin.yaml
  - pvc-pgadmin.yaml
  - pvc-minio.yaml
  - postgresql-cluster.yaml
  - postgresql-backup.yaml
  - configmap-pgadmin.yaml
  - service-minio.yaml

namespace: fake-namespace

namePrefix: amt-

labels:
  - pairs:
      minbzk.github.io/name: amt
    includeSelectors: true

buildMetadata: [originAnnotations]
