apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # https://stackoverflow.com/questions/56126864/why-do-i-get-502-when-trying-to-authenticate
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: nginx
  rules:
    - host: keycloak.apps.digilab.network
      http:
        paths:
          - backend:
              service:
                name: svc
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - keycloak.apps.digilab.network
      secretName: keycloak-tls
