apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - postgresql-cluster.yaml
  - postgresql-backup.yaml

namespace: fake-namespace

namePrefix: keycloak-

commonLabels:
  minbzk.github.io/name: keycloak

buildMetadata: [originAnnotations]
