apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-tad-staging

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml

commonAnnotations:
  commithash: "replacehash"
  minbzk.github.io/version: "0.1.0"

images:
  - name: tad-image
    newName: ghcr.io/minbzk/tad
    newTag: pr-33@sha256:cf4cbdb5a692a52ebf55b74f8fb821c25cc8b8f3a9768100c5099a8c92173f9d

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: tad.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: tad.stag.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.stag.apps.digilab.network
