apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-amt-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: tn-ai-validation-amt
