apiVersion: v1
stringData:
    minio_root_user: ENC[AES256_GCM,data:uxUBd14b5kUQZ9M7bwA=,iv:OAaxrQ8cG3xbvvCkdHeaNUcmG6q+tZ42VHBxv0/BtdU=,tag:b5Vwe7spjR3HWozhRGGGnA==,type:str]
    minio_root_password: ENC[AES256_GCM,data:pozIcQxS7jMpI4WgHBY=,iv:vSHDl1SIp/bT8umKls318clXh/3nSXL06jviuC2q6HY=,tag:hHY5jlD6Letl8HWXL9183w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sec-minio
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tzxxf0sp4hpyqygwzwnuj4lrhn33c2kq4yce9w8my84vpvx23duscc9qgc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1ovWGNoSitmMmRMQ2pQ
            MlJET3M5bzdIWUxzL2Nic1NVV25ZaitOdndZCnZUanlsZnVWYjBTSFIwR09QSXlC
            UmRaTk5CaHRMM2VXRzNVRFBQUTVzclUKLS0tIHJ3V1BKc0c3U0JlOWdsNzVnNDIy
            b3QxRzF1WXo0UzdIeEhsNU13SVlFVXcKyPAt/rSGDIj+UouO67famrDUPkLk2KlT
            /vIcm9nBTdV97i5V+tEkag9iOqsZnYbdaVAtWGqAOt6PMM3QOizPKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T11:36:16Z"
    mac: ENC[AES256_GCM,data:myCBIDuBTkd/bSyxzSDratrgyFPTRRgfYPYl0dC2bod5/GpWc91SF87WaStpBBejGha7IoETDIKVsup9l5L+HdF2AkZBlpyToZvjEbYBd7u8W8l8+YedfZEyw7fMmXHEpwFYMhEDHUOptpBe4/EaNVCV1EeAKR2rZnvT58GK7HQ=,iv:QKogw233H+ai0okofhbTFUaCTcjdH+em0cYnglh5RMQ=,tag:sM2DmICXMDCDAdabKOu0wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
