apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefullset.yaml
  - service.yaml
  - ingress.yaml

namespace: placeholder

namePrefix: vault-

commonLabels:
  minbzk.github.io/name: vault

buildMetadata: [originAnnotations]

configMapGenerator:
  - name: vault-config
    files:
      - config.hcl
