apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-tad-staging

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: pr-72

images:
  - name: tad-image
    newName: ghcr.io/minbzk/tad
    newTag: pr-72@sha256:6880e9fb41cfb641f88a5e3184fcf4c04c243433ab6c3b34b9900a2f7058c7fe

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: tad.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: tad.stag.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.stag.apps.digilab.network
