apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-tad-staging

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: main

images:
  - name: tad-image
    newName: ghcr.io/minbzk/tad
    newTag: main@sha256:e610d235b72661f8cf8f589fc6f1b83437e68afd7335e92bd9a7bb9efb2a640d

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: tad.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: tad.stag.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.stag.apps.digilab.network
