apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-tad-staging

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml

commonAnnotations:
  commithash: bef73f66990e61639a06b0f3097e84a5bf43f4f0
  minbzk.github.io/version: main }

images:
  - name: tad-image
    newName: ghcr.io/minbzk/tad
    newTag: main@sha256:22ef7fee5a34301b092579542b2928329e50d27f1183469481feb295af0854c6

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: tad.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: tad.stag.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.stag.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.stag.apps.digilab.network
