apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - postgresql-cluster.yaml
  - postgresql-backup.yaml


namespace: fake-namespace

namePrefix: wiki-

commonLabels:
  minbzk.github.io/name: wiki

buildMetadata: [originAnnotations]
