apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-llm-benchmarks
namePrefix: llm-benchmarks-

resources:
  - ../../base

images:
  - name: frontend-image
    newName: nginx
    newTag: mainline
patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: ai-validation-llm-benchmarks.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: ai-validation-llm-benchmarks.apps.digilab.network
