apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-infra
namePrefix: prod-

resources:
  - ../../base

images:
  - name: vault-image
    newName: hashicorp/vault
    newTag: 1.16.1

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: vault.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: vault.apps.digilab.network
