apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-old.yaml

namespace: tn-ai-validation-ai-verordening-beslishulp

namePrefix: ai-verordening-beslishulp-

commonLabels:
  minbzk.github.io/name: ai-verordening-beslishulp

buildMetadata: [originAnnotations]

commonAnnotations:
  commithash: b5967d17d0433266a40a3f391d34b09b386e9ee8
  minbzk.github.io/version: main

images:
  - name: ai-verordening-beslishulp-image
    newName: ghcr.io/minbzk/ai-verordening-beslishulp
    newTag: main@sha256:4ce3075ef0bea25e0e3e9930fd5aef5b3e8ffef42782c03eb9dc4c8bea534a7c
