apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - postgresql-backup.yaml
  - minio-backup-scripts.yaml

patches:
  - path: postgresql-cluster-backup-patch.yaml
    target:
      kind: Cluster
      name: cluster-db
# Only uncomment this patch within a new cluster, adding bootstrap to an existing deployment can cause problems!
#  - path: postgresql-cluster-bootstrap-patch.yaml
#    target:
#      kind: Cluster
#      name: cluster-db
  - path: minio-backup-patch.yaml
    target:
      kind: Deployment
      name: dpl-minio
