apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cluster-daily-backup
spec:
  schedule: "0 0 0 * * *" # Daily at 0:00 UTC
  backupOwnerReference: self
  cluster:
    name: cluster-db
