apiVersion: v1
kind: Secret
metadata:
    name: sec-postgres
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:AOxvH6TV/fbm5H2f2No=,iv:u7mPa23NT7nwfNeKAynrVIxpc4m1aY4VqodGvepiReE=,tag:ronzKaqtYKtBtU7OwhzO5A==,type:str]
    username: ENC[AES256_GCM,data:mM4bYnenPmo=,iv:dShb0UajRmCXJuSpLUf/foRj27DdNZFuRyQGC4R3h6Q=,tag:47D5a5tu4PvgPcBRX2pGVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f7z0780s30xvm05c7h25l8lwmcxkw24rz0egc2g7vglncmft04esjd7uga
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ01ZNUE4ODFWMkgyZHY0
            L1RNL0dJejBzdW5ieVVBeFRMSmZPY2sxN2c4Ckp1TExKaW9xV0tOUlR3K3dMNHB0
            dktjNTJvL3A0KzlqWWRTUEtGL1pYaW8KLS0tIHdLdTRwNnErYUlObHFaRUFVaDEx
            Unpic3hoakZ0dDRKU3JjSURkSDk1MDQK/HchRElLWSn5VJlpTp+e/hwHyICden+o
            qq5fZjKtkK70pRezKnQudCmL1L+BhKQN1SlDHPmEym2RKACOX9Y5MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-01T08:57:18Z"
    mac: ENC[AES256_GCM,data:neuKgctVY5Ka48MhHViY7mzTw4RFuIYp79U3u9wkeoS0aC4nZzFvmW4OEBfXWfzpLd3B7d6F94NgmGEpCJjjzcn3e9rRQm7Zq1TjPoVCwqkaDmLNBUCv6AoUizCl9dSfW6HroXrQ0i41x/56TYM1KON1VkPDv00SxvgH5035tws=,iv:KOS6bcJKV3gsRE7VxAP8a4f+9CZiMugXljCpKDw006M=,tag:itwBX44HN12rCrBSkVFqGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
