apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: tn-ai-validation-instrument-registry

namePrefix: instrument-registry-

commonLabels:
  minbzk.github.io/name: instrument-registry

buildMetadata: [originAnnotations]

commonAnnotations:
  commithash: xx
  minbzk.github.io/version: main

images:
  - name: instrument-registry-image
    newName: ghcr.io/minbzk/instrument-registry
    newTag: main@sha256:57e29f958f2a0cccd98975a282b6985ea5b36f3c51474266e0aca0c535e1ec7a
