apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flagd
  name: flagd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flagd
        app: flagd
    spec:
      automountServiceAccountToken: false
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:v0.10.3
          volumeMounts:
            - name: config-volume
              mountPath: /etc/flagd
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8014
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8014
            initialDelaySeconds: 5
            periodSeconds: 60
          ports:
            - containerPort: 8013
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
              ephemeral-storage: "2Gi"
            requests:
              cpu: 100m
              memory: 64Mi
          args:
            - start
            - --uri
            - file:/etc/flagd/config.json
      volumes:
        - name: config-volume
          configMap:
            name: open-feature-flags
            items:
              - key: open-feature-flags.json
                path: config.json
