apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-amt

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: chisel-server
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: chisel.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: chisel.prd.apps.digilab.network
