apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-amt

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml
  - secret-oidc.yaml
  - secret-minio.yaml
  - secret-azure-backup.yaml

components:
  - ../../base/components/backup

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: v0.4.0

images:
  - name: amt-image
    newName: ghcr.io/minbzk/amt
    newTag: v0.4.0@sha256:5c2c3e2a65c01fd09fd3d2158154990d02aafcb0e1fce44318c8e440224fd72c

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: amt.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: amt.prd.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.prd.apps.digilab.network
