apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-amt

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: main

images:
  - name: amt-image
    newName: ghcr.io/minbzk/amt
    newTag: main@sha256:00cb97816a3e417a1871ac4288413168007fc7552266135c0121664e9751b3d3

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: amt.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: amt.prd.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.prd.apps.digilab.network
