apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-amt

resources:
  - ../../base
  - ../../migration/chivel/overlays/production
  - ingress-redirect.yaml
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml
  - secret-oidc.yaml
  - secret-minio.yaml
  - secret-azure-backup.yaml

components:
  - ../../base/components/backup

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: main

images:
  - name: amt-image
    newName: ghcr.io/minbzk/amt
    newTag: main@sha256:0736998003d1bd700bdaf2e42c1639a4f9d069fd94a233c6086bbba4d135d325

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: amt.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: amt.prd.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.prd.apps.digilab.network
