apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-ai-validation-amt

resources:
  - ../../base
  - secret-pgadmin.yaml
  - secret-postgres.yaml
  - secret-postgres-super.yaml
  - secret-oidc.yaml

commonAnnotations:
  commithash: 1094faa50c7faad46dc932ff3b86aeb961c9fe6f
  minbzk.github.io/version: main

images:
  - name: amt-image
    newName: ghcr.io/minbzk/amt
    newTag: main@sha256:542b2a93fe2d84887e0f77fd590d8e87944cc063a2b8f9f1c90a5f997e1719df

patches:
  - target:
      kind: Ingress
      name: ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: amt.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: amt.prd.apps.digilab.network
  - target:
      kind: Ingress
      name: ing-pgadmin
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: pgadmin.prd.apps.digilab.network
      - op: replace
        path: /spec/tls/0/hosts/0
        value: pgadmin.prd.apps.digilab.network
