apiVersion: v1
data:
    access_key: ENC[AES256_GCM,data:mvmwHufpcnGtqHTa7A==,iv:rhF8t6XqYgf0msZV3RQfQqqHIPgNCRyZpWyktmxBXXA=,tag:CgVkljoYWNIs1yHL4SBQDg==,type:str]
    secret_key: ENC[AES256_GCM,data:vF2bpFRNg6XfZHU1py4=,iv:WDwodvRIV3NJ1yRcs/WApww42/9z/YzPPCZFDOW3EZw=,tag:qdbnp5ecmdA4k0xCTRJFww==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: sec-minio
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0deq3t66yld72t4p8eawngpreffrsvztaffhj7f3wccercdx4psy5mvl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNktDVmFoQkVVR2NueU8y
            clN2TEUySzR3Zk4xVG1HNnhKVXBQci95MVZZCmxGMUpkWi9FSjJtRm9RWXZxS3pX
            cUVPSXZZdjY5ZUJtRVVyNlVycU1tWTAKLS0tIFBSdnE1QXl5cjRWVnVmZjJZNGU3
            OVhJa2tTeDdJWnRxTTRsZEtmTHRLZmcK1L+b5y0hq8L46feQjiRSRjWVFzn3HwTQ
            uGbt5ADfJ/gsLYhX7Q0Ryo5RVDcXvmQhsC+Q7u5yp8Te4EC9VGM7hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T14:33:31Z"
    mac: ENC[AES256_GCM,data:60yMgoFNXCtFNYpi4HteNIP83nRC4Mdn4zmuVLkk8uTAWRVTlC/xjdBOhomdr6YfsP4mpZZM+jLBbP1TaZ+kVJjh8uIK9WyMyS458NNNf7KyOI6yt/zQbYiAjHb9xWd0HK9ubZZUgLBiUKaADxGpV7RrAr9+ZyqIn5sfbcqUdOg=,iv:xmms24oHXCozhsc0NxTJi2nQWB0bHs+yflMWJI/f82I=,tag:QY1Rd2VKZhTM0DxhnbUxDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
