apiVersion: v1
kind: Secret
metadata:
    name: sec-pgadmin
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:4bsKASexGhKsO6EYLUVlDg==,iv:L5TGHJELbV9QadnqlPuPmJyT2VWxNh+ONLFBXZ5TTEk=,tag:05n7I9St0DzFnYJL68EkwA==,type:str]
    email: ENC[AES256_GCM,data:1rMqV1kU3fdTqM52gT6jQIRVYLipzw==,iv:6W5b7kY0e+CSV5xhwClTm5CqhxJU1D4QfyvCFryFmJQ=,tag:gkpmbAACrq/ka8YC4cPh4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0deq3t66yld72t4p8eawngpreffrsvztaffhj7f3wccercdx4psy5mvl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZG5mbW1ZMTZDdlBCaExj
            d3pZU2MrbDlaRWpBYU5pVGhWcXFOUlRMRFh3CitPOUF6NHk0S3l6R2Y1M1JyNlBL
            TzloQ0UyMDFLN1k0cThXb2xTVVRJOGsKLS0tIHIrbXRDbVdVNnM0NG9yRDE4bEZ1
            RUgyQ2NWMm5aenBvN2V2WDhtbW9abWsKaxlD/f/w2wt+QRlFOUlv/uMI9w/p1Oyw
            t6BGxo+5UyTTkaKnZFCTP7Bfutkd6uUfFRJw3YHOZ3TG46pSUwyZFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T19:01:18Z"
    mac: ENC[AES256_GCM,data:hLuOHIKfFOZflL3DY3pPUZ1m84SlWsdsybhm7q+4p6oXgLsqtAM2kSQNniYyID2O/CcOaeu59/XdDjqLRu1teP+rqMD0lL8LzBRkWJVquib4oHb2IJOZ6WO/I474SoZeHx6ah5kpFvU0vTZiZr7AHhDQWnNo5ZbHjZR9ag8LbwU=,iv:2yFttqYs6ETjRNJasnz/7Hoi4k3LVTEji5V2n16WbkI=,tag:YmbBW/R507schmHiB3RwyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
