apiVersion: v1
kind: Secret
metadata:
    name: sec-postgres
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:QjSncvUECidT71TSfzNO5w==,iv:LVB6rBbY/e1B+KBNJxVZ3U3iNa2lPzD82y6+umPKl9M=,tag:pbuNQk/5fe5foNdGJmMdBg==,type:str]
    username: ENC[AES256_GCM,data:Qxwp,iv:hhgso5k4F/uIo+BURuoN7M4e18K9K+A7vRHEUTF2eZk=,tag:Cc8lRk1ZPksgj+ZcOay/wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0deq3t66yld72t4p8eawngpreffrsvztaffhj7f3wccercdx4psy5mvl7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMk5UaVI3c3ZEdDJndEhO
            bDR2dzdhL0NsdGFtSFoxa0ZUTWJ2eUltV2wwCjh0SmRXanFNZHNXeHE4L3k0aUx2
            Y1lFUkpSVFVTaFoyVWV1OVFsd3BCTUkKLS0tIEtFMmRGeG9TSFZDRE9PMEhpTnV3
            ZVBzWFFrUG9Rc1pnSDZDaEZxcEZpWWMKHkOjcRMklMG1vAIO7aSkxaoiHc6EJfub
            JKoDtQnri87yS8oOG91L2iQclAyJgh3DVcK8mja2xHLV0xnH45A2WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-26T19:01:29Z"
    mac: ENC[AES256_GCM,data:WNb127TsQStH18/TETuCeOXfNFnm6CTAqdZIt7m1xZw3sMB/LZ+RjsYHavYG43zSexHLGculG8VnTsZ3eCQyyA6AITlIyrjj3UvWa1B7Dapts+oJ96Ke16ztDQE5154FzVmBHSBea7WbV0MlvpQ9SExDiiy5UrRys5ZknLAUmLM=,iv:d+8BYOAnvvQIWcpcl4bRcEj/wwWFlGCsS0rgvoq6nu0=,tag:mqnK1DoVQYEaA0h/w7/Y/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
